### PR TITLE
Possible fix to the exit 1 bug

### PR DESCRIPTION
**Pull request by Rubemlrm**
I've tested the status 1 wrong script success. Since we are throwing the exit 1 inside the try catch block , looks that powershell sometimes handles this in weird way. 
With some testing , i've throwed some status 1 code and after that run in the powershell the $? to get the last command exit status and everytime it return that the code runned without problems. 
After that i've tried collect the number of errors and throw a status 1 in the end of script ,and in the way looked that worked.
I've tested remove the try / catch block and run the script with errors and i got a last runned command with success too :/ .

### CODE REVIEW

**Comment by joergi** [comment]
... I will have look on Friday or Saturday to it! Thanks!

**Comment by joergi** [comment]
at the moment there is a problem with the powershell container.
grafik

https://travis-ci.org/joergi/MagPiDownloader/jobs/290616821

**Comment by Rubemlrm** [comment]
Fixed the powershell command not found , looks that microsoft changed the command name on dockerfile for powershell

**Comment by joergi** [comment]
Thx for this quick fix

**Pull request merged**
