### PR TITLE
Updated travis.yml to run powershell

### PR DESCRIPTION
**Pull request by Rubemlrm**
After several test and with lots of try/error commits , i've setted a travis.yml file that will run bash and powershell scripts. 
For the powershell scripts i'm using the official powershell docker image. I've disabled the magpi-issue-downloader.ps1 test to avoid a long wait since this script it will download all issues of magazine.

this pull request is a possible solution for issue #8

### CODE REVIEW

**Comment by joergi** [comment]
@Rubemlrm - just to let you know, I added yesterday the exit code 1 for the scripts if an error appeared. Else it was still ending with exit code 0, even if an error appeared!

**Comment by Rubemlrm** [comment]
@joergi i will try that tomorrow , can you commit that situation to other branch just for testing ?

**Comment by joergi** [comment]
@Rubemlrm I adapted your work for another version.

https://github.com/joergi/DatenSchleuderDownloader/blob/3590a631927e88adec4d681882dc8d2bf0669ed2/datenschleuder_download.ps1

that one will fail, but it will leave travis with code 0 aka green

**Comment by joergi** [comment]
@Rubemlrm - you can see it here: https://travis-ci.org/joergi/DatenSchleuderDownloader/builds/289255717

**Pull request merged**
