### PR TITLE
Issues #21 refactoring the sources of the issues to download

### LINKED ISSUE #21: All special edition downloaders should be using the same file for all OS
At the moment the Linux and the Windows downloaders don't have the sources duplicated.   
For each special downloader should be a file which only contains the links, and the downloaders should deal with it

For example:
Windows for Essentials_Games_v1: https://github.com/joergi/MagPiDownloader/blob/master/windows/magpi-special-issue-downloader.ps1#L21
Linux for Essentials_Games_v1: https://github.com/joergi/MagPiDownloader/blob/master/linux_mac/magpi-special-issue-downloader.sh#L21

keep it simple, one file to serve both downloaders.

Similar to https://github.com/joergi/Hackspace-Magazine-Downloader/issues/5

### PR DESCRIPTION
**Pull request by joergi**
close #21 

using a single file for all OS

### CODE REVIEW

**Comment by Rubemlrm** [comment]
@joergi can we merge this already? Or do you want to fix the travis-ci and codacy not running steps ?

**Comment by joergi** [comment]
It's a draft 😉
But I will sit later at my pc and finish some stuff

**Comment by Rubemlrm** [comment]
> 
> 
> It's a draft 😉
> But I will sit later at my pc and finish some stuff

roger that =)

**Comment by joergi** [comment]
First fix: https://github.com/joergi/WireframeDownloader/pull/6/files

**Pull request merged**
